apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: autodeploy
  labels:
    app: nginx-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-sample-app
  template:
    metadata:
      labels:
        app: nginx-sample-app
    spec:
      containers:
      - name: nginx 
        image: bhatuse2/nginx:356a0dd749f0c22052658bdd7250135eb137e28a
        ports:
        - containerPort: 80