apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: autodeploy
  labels:
    app: nginx-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-sample-app
  template:
    metadata:
      labels:
        app: nginx-sample-app
    spec:
      containers:
      - name: nginx 
        image: bhatuse2/nginx:9345a4d4951226c11eafcb5be193d3feae59660d
        ports:
        - containerPort: 80
